/**:
  ros__parameters:
    input:
      point_cloud: "/camera/camera/depth/color/points" # d435i Pointcloud
      # pose_covariance: "/camera/camera/pose"
      pose_covariance: "/camera/camera/pose_covariance" # Odom / localization need
    output:
      raw_map: raw_elevation_map